
-- Create the 'products' table
CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    category text,
    price numeric,
    description text,
    benefits text,
    usage text,
    ingredients text,
    imageUrl text
);

-- Create the 'articles' table
CREATE TABLE public.articles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    category text,
    content text,
    date timestamp with time zone,
    imageUrl text
);

-- Add comments to describe the tables for better documentation
COMMENT ON TABLE public.products IS 'Stores all product information';
COMMENT ON TABLE public.articles IS 'Stores all blog articles';
